name: Node.js CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Build development version
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: sibmei-unstable-${{ env.COMMIT_SHORT_SHA }}
        path: build/release
